=== MohamedIttioui/Lenguaje-Marcas/lmsgi_pack4_ud4/lmsgi_pack4_ud4_Mohamed_Ittioui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabecera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:attribute name="dia" type="xs:positiveInteger"
                                        use="required" />
                                    <xs:attribute name="mes" type="xs:positiveInteger"
                                        use="required" />
                                    <xs:attribute name="any" type="xs:positiveInteger"
                                        use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cliente" type="ClienteProveedor" />
                            <xs:element name="proveedor" type="ClienteProveedor" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="linea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="articulo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="precios">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="sin-IVA" type="moneda" />
                                                    <xs:element name="con-IVA" type="moneda" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="IVA">
                                            <xs:complexType>
                                                <xs:attribute name="tipos-IVA" type="xs:string"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="num-unidades" type="xs:integer" />
                            <xs:element name="import-total" type="moneda" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:IDREF" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="total">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subtotal">
                                <xs:complexType>
                                    <xs:attribute name="IVA-4" type="moneda" use="required" />
                                    <xs:attribute name="IVA-10" type="moneda" use="required" />
                                    <xs:attribute name="IVA-21" type="moneda" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="total-sin-IVA" type="moneda" />
                            <xs:element name="total-con-IVA" type="moneda" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="moneda">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+(\.[0-9]{1,3})? (€|$|£)"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ClienteProveedor">
        <xs:attribute name="nom-fiscal" type="xs:string" use="required" />
        <xs:attribute name="nom-comercial" type="xs:string" use="optional" />
        <xs:attribute name="NIF" type="xs:string" use="required" />
    </xs:complexType>

</xs:schema>

=== MohamedIttioui/Lenguaje-Marcas/lmsgi_pack4_ud4/lmsgi_pack4_ud4_Mohamed_Ittioui.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-model href="lmsgi_pack4_ud4_Mohamed_Ittioui.dtd" type="application/xml-dtd"?> -->

<factura xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="lmsgi_pack4_ud4_Mohamed_Ittioui.xsd">
    <cabecera id="01">
        <fecha dia="01" mes="01" any="2001" />
        <cliente nom-fiscal="Cliente 1" NIF="AS2134" />
        <proveedor nom-fiscal="Proveedor 1" nom-comercial="Proveedor A" NIF="231DS" />
    </cabecera>

    <linea id="articte-ref-1">
        <articulo id="articte-ref-1">
            <descripcion>Una descripcion del artículo</descripcion>
            <precios>
                <sin-IVA>17 €</sin-IVA>
                <con-IVA>17.68 €</con-IVA>
            </precios>
            <IVA tipos-IVA="4" />
        </articulo>
        <num-unidades>3</num-unidades>
        <import-total>53.04 €</import-total>
    </linea>

    <linea id="articte-ref-2">
        <articulo id="articte-ref-2">
            <descripcion>Una descripcion del artículo</descripcion>
            <precios>
                <sin-IVA>25 €</sin-IVA>
                <con-IVA>27.5 €</con-IVA>
            </precios>
            <IVA tipos-IVA="10" />
        </articulo>
        <num-unidades>5</num-unidades>
        <import-total>137.5 €</import-total>
    </linea>

    <total>
        <subtotal IVA-4="26 €" IVA-10="27.5 €" IVA-21="30.25 €" />
        <total-sin-IVA>75 €</total-sin-IVA>
        <total-con-IVA>137.5 €</total-con-IVA>
    </total>
</factura>
