=== MohamedIttioui/Lenguaje-Marcas/UD4_pack5_xml/lmsgi_pack5_5.3_Mohamed_Ittioui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="objectes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="objecte" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propietari" type="xs:string" />
                            <xs:element name="preu_sortida" type="preu" />
                            <xs:element name="preu_minim" type="preu" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="preu">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="6" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== MohamedIttioui/Lenguaje-Marcas/UD4_pack5_xml/lmsgi_pack5_5.3_Mohamed_Ittioui.xml
<?xml version="1.0" encoding="UTF-8"?>
<objectes xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="lmsgi_pack5_5.3_Mohamed_Ittioui.xsd">
    <objecte>
        <propietari>Maria García</propietari>
        <preu_sortida>1000.00</preu_sortida>
        <preu_minim>600.00</preu_minim>
    </objecte>
    <objecte>
        <propietari>Joan López</propietari>
        <preu_sortida>2500.50</preu_sortida>
    </objecte>
    <objecte>
        <propietari>Ana Ruiz</propietari>
        <preu_sortida>9999.99</preu_sortida>
        <preu_minim>8500.00</preu_minim>
    </objecte>
</objectes>
